default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= Rails.application.credentials.dig(:development, :database, :database) %>
  username: <%= Rails.application.credentials.dig(:development, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :database, :password) %>
  host:     <%= Rails.application.credentials.dig(:development, :database, :host) %>

test:
  <<: *default
  database: <%= Rails.application.credentials.dig(:test, :database, :database) %>
  username: <%= Rails.application.credentials.dig(:test, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:test, :database, :password) %>
  host:     <%= Rails.application.credentials.dig(:test, :database, :host) %>

production:
  <<: *default
  database: <%= Rails.application.credentials.dig(:production, :database, :database) %>
  username: <%= Rails.application.credentials.dig(:production, :database, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :database, :password) %>
  host:     <%= Rails.application.credentials.dig(:production, :database, :host) %>
